export const quizData = {
  categories: [
    {
      id: "javascript_basic",
      name: "Javascript Basic",
      description: "Test your fundamental JavaScript knowledge",
      questions: [
        {
          id: "q1",
          question: "Which method can be used to round a number to the nearest integer in JavaScript?",
          options: [
            "This method rounds a number up to the nearest integer, regardless of its decimal part.",
            "This method rounds a number down to the nearest integer, ignoring the decimal part.",
            "This method rounds a number to the nearest integer based on its decimal value.",
            "This method generates a random number between 0 and 1, without rounding.",
          ],
          correctAnswer: "This method rounds a number to the nearest integer based on its decimal value.",
          timeLimit: 10,
        },
        {
          id: "q2",
          question: "What is the correct syntax for referring to an external script called 'script.js'?",
          options: [
            "<script name='script.js'>",
            "<script href='script.js'>",
            "<script src='script.js'>",
            "<script file='script.js'>",
          ],
          correctAnswer: "<script src='script.js'>",
          timeLimit: 10,
        },
        {
          id: "q3",
          question: "Which company developed JavaScript?",
          options: ["Microsoft", "Netscape", "Google", "Mozilla"],
          correctAnswer: "Netscape",
          timeLimit: 10,
        },
        {
          id: "q4",
          question: "What does 'typeof null' return in JavaScript?",
          options: ["'null'", "'undefined'", "'object'", "'boolean'"],
          correctAnswer: "'object'",
          timeLimit: 10,
        },
        {
          id: "q5",
          question: "Which method is used to add an element to the end of an array?",
          options: ["push()", "pop()", "shift()", "unshift()"],
          correctAnswer: "push()",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "angular_basic",
      name: "Angular Basic",
      description: "Fundamental Angular concepts and patterns",
      questions: [
        {
          id: "a1",
          question: "What is Angular?",
          options: [
            "A JavaScript library for building user interfaces",
            "A TypeScript-based web application framework",
            "A CSS framework for responsive design",
            "A database management system",
          ],
          correctAnswer: "A TypeScript-based web application framework",
          timeLimit: 10,
        },
        {
          id: "a2",
          question: "What is a component in Angular?",
          options: [
            "A service that handles HTTP requests",
            "A directive that manipulates the DOM",
            "A class that controls a part of the screen called a view",
            "A module that groups related functionality",
          ],
          correctAnswer: "A class that controls a part of the screen called a view",
          timeLimit: 10,
        },
        {
          id: "a3",
          question: "What is dependency injection in Angular?",
          options: [
            "A way to create components dynamically",
            "A design pattern for providing dependencies to a class",
            "A method for routing between pages",
            "A technique for data binding",
          ],
          correctAnswer: "A design pattern for providing dependencies to a class",
          timeLimit: 10,
        },
        {
          id: "a4",
          question: "What is the Angular CLI?",
          options: [
            "A code editor for Angular development",
            "A command-line interface for Angular development",
            "A testing framework for Angular applications",
            "A deployment tool for Angular apps",
          ],
          correctAnswer: "A command-line interface for Angular development",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "react_advance",
      name: "React.js Advance",
      description: "Advanced React concepts and patterns",
      questions: [
        {
          id: "r1",
          question: "What is the purpose of React.memo()?",
          options: [
            "To memoize expensive calculations",
            "To prevent unnecessary re-renders of functional components",
            "To manage component state",
            "To handle side effects",
          ],
          correctAnswer: "To prevent unnecessary re-renders of functional components",
          timeLimit: 10,
        },
        {
          id: "r2",
          question: "What is the difference between useMemo and useCallback?",
          options: [
            "useMemo memoizes values, useCallback memoizes functions",
            "useMemo is for state, useCallback is for effects",
            "useMemo is synchronous, useCallback is asynchronous",
            "There is no difference between them",
          ],
          correctAnswer: "useMemo memoizes values, useCallback memoizes functions",
          timeLimit: 10,
        },
        {
          id: "r3",
          question: "What is a Higher-Order Component (HOC)?",
          options: [
            "A component that renders other components",
            "A function that takes a component and returns a new component",
            "A component with higher priority in rendering",
            "A component that uses advanced React features",
          ],
          correctAnswer: "A function that takes a component and returns a new component",
          timeLimit: 10,
        },
        {
          id: "r4",
          question: "What is the purpose of useReducer hook?",
          options: [
            "To reduce bundle size",
            "To manage complex state logic",
            "To reduce re-renders",
            "To handle HTTP requests",
          ],
          correctAnswer: "To manage complex state logic",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "flutter",
      name: "Flutter",
      description: "Flutter mobile development framework",
      questions: [
        {
          id: "f1",
          question: "What programming language is Flutter primarily based on?",
          options: ["Java", "Kotlin", "Dart", "Swift"],
          correctAnswer: "Dart",
          timeLimit: 10,
        },
        {
          id: "f2",
          question: "What is a Widget in Flutter?",
          options: [
            "A small application",
            "A building block of Flutter UI",
            "A database connection",
            "A testing framework",
          ],
          correctAnswer: "A building block of Flutter UI",
          timeLimit: 10,
        },
        {
          id: "f3",
          question: "What is the difference between StatelessWidget and StatefulWidget?",
          options: [
            "StatelessWidget can change, StatefulWidget cannot",
            "StatelessWidget cannot change, StatefulWidget can change",
            "There is no difference",
            "StatelessWidget is for web, StatefulWidget is for mobile",
          ],
          correctAnswer: "StatelessWidget cannot change, StatefulWidget can change",
          timeLimit: 10,
        },
        {
          id: "f4",
          question: "What is hot reload in Flutter?",
          options: [
            "A way to restart the entire application",
            "A feature that allows you to see changes instantly without losing app state",
            "A method to deploy apps to production",
            "A debugging technique",
          ],
          correctAnswer: "A feature that allows you to see changes instantly without losing app state",
          timeLimit: 10,
        },
      ],
    },
  ],
}
